version: 2.1

#Anchor and alias for the docker image:circleci/node:13.8.0
defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build-frontend:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

workflows:
  default:
    jobs:
      - build-frontend
    